export const routes = {
  home: "/",
  student: {
    home: "/student",
    courses: "/student/courses",
    course: (id: string) => `/student/courses/${id}`,
    tools: "/student/tools",
    tool: (tool: string) => `/student/tools/${tool}`,
    assignments: "/student/assignments",
    assignment: (id: string) => `/student/assignments/${id}`,
    officeHours: "/student/office-hours",
    progress: "/student/progress",
    settings: "/student/settings",
  },
  instructor: {
    home: "/instructor",
    courses: "/instructor/courses",
    course: (id: string) => `/instructor/courses/${id}`,
    content: "/instructor/content",
    assessment: "/instructor/assessment",
    qna: "/instructor/qna",
    analytics: "/instructor/analytics",
    settings: "/instructor/settings",
  },
  governance: {
    home: "/governance",
    models: "/governance/models",
    sources: "/governance/sources",
    access: "/governance/access",
    policies: "/governance/policies",
    audit: "/governance/audit",
    incidents: "/governance/incidents",
    incident: (id: string) => `/governance/incidents/${id}`,
    adoption: "/governance/adoption",
  },
}
